# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jON7AkrDBurv0kA5aAKAmgE7Z7k25Qt2
"""

# Install required packages
!pip -q install gradio transformers accelerate torch textblob pandas matplotlib

print("✓ Installation complete")

import gradio as gr
from transformers import pipeline
import pandas as pd
from textblob import TextBlob
from datetime import datetime
import matplotlib.pyplot as plt

print("✓ Libraries imported")

# Suppress warnings
import warnings
warnings.filterwarnings('ignore')

# load the model
# Load LLM pipeline (handles all model loading internally)

chat_pipeline = pipeline(
    "text-generation",
    model="distilgpt2",  # Much smaller, runs in seconds or "microsoft/Phi-3-mini-4k-instruct",
    device_map="auto"  # Uses GPU if available
)

print("✓ Model loaded")

# Define Response Function
def respond(message, history):
    """
    Core chat function - takes user message and returns AI response

    Args:
        message: str - Current user input
        history: list - Previous conversation turns

    Returns:
        str - AI response text
    """
    # Format prompt for instruction-tuned model
    formatted_message = f"<|user|>\n{message}<|end|><|assistant|>"

    # Generate response
    response = chat_pipeline(
        formatted_message,
        max_new_tokens=256,  # Limit length for speed
        temperature=0.7,      # Creative but not chaotic
        do_sample=True        # Enables sampling
    )

    # Extract text from response structure
    ai_response = response[0]["generated_text"]

    # Strip the user message portion to return only assistant part
    if "<|assistant|>" in ai_response:
        ai_response = ai_response.split("<|assistant|>")[-1].strip()

    # Set clean_up_tokenization_spaces
    response = chat_pipeline(
        formatted_message,
    max_new_tokens=256,
    temperature=0.7,
    do_sample=True,
    clean_up_tokenization_spaces=False  # Silences BPE warning
)

    return ai_response

print("✓ Response function defined")

# Add metrics calculator
def calculate_metrics(text):
    """
    Calculate discourse metrics from text input

    Returns:
        dict - Dictionary of calculated metrics
    """
    blob = TextBlob(text)

    metrics = {
        'timestamp': datetime.now().strftime('%H:%M:%S'),
        'char_length': len(text),
        'word_count': len(blob.words),
        'sentence_count': len(blob.sentences),
        'avg_word_length': sum(len(w) for w in blob.words) / len(blob.words) if blob.words else 0,
        'sentiment_score': round(blob.sentiment.polarity, 3),
        'complexity_estimate': len(blob.words) / len(blob.sentences) if blob.sentences else 0
    }

    return metrics

# Store conversation history
conversation_log = []

def respond_with_metrics(message, history):
    """
    Wrapper that captures message metrics before returning response
    """
    global conversation_log

    # Calculate metrics for user message
    user_metrics = calculate_metrics(message)

    # Get AI response
    ai_response = respond(message, history)

    # Calculate metrics for AI response
    ai_metrics = calculate_metrics(ai_response)

    # Log full turn
    turn_log = {
        'turn_number': len(conversation_log) + 1,
        'user_input': message,
        'ai_response': ai_response,
        'user_metrics': user_metrics,
        'ai_metrics': ai_metrics
    }

    conversation_log.append(turn_log)

    # Return response and formatted metrics display
    metrics_display = f"""
📊 **Turn #{turn_log['turn_number']} Metrics:**
─────────────────────────────────────
User Input:
  • Length: {user_metrics['word_count']} words | {user_metrics['char_length']} chars
  • Sentences: {user_metrics['sentence_count']}
  • Avg Word: {user_metrics['avg_word_length']:.1f} chars

AI Response:
  • Length: {ai_metrics['word_count']} words | {ai_metrics['char_length']} chars
  • Sentences: {ai_metrics['sentence_count']}
  • Sentiment: {ai_metrics['sentiment_score']:.2f} (-1 to +1)

💡 *Higher meaning load may indicate greater cognitive burden*
    """.strip()

    return ai_response, metrics_display

print("✓ Metrics calculator ready")

# Create the interface with dual output (chat + metrics)
with gr.Blocks(title="Deliberation Component Prototype") as demo:

    gr.Markdown("""
    # 🗣️ Deliberation Component Prototype

    Interactive system for measuring discourse metrics in citizen-AI dialogue.

    **Purpose:** Quantify interpretive burden and meaning load in democratic engagement conversations.
    """)

    with gr.Row():
        # Left side: Chat interface
        with gr.Column(scale=2):
            chatbot = gr.ChatInterface(
                respond_with_metrics,  # Changed to respond_with_metrics for metrics
                title="Dialogue",
                description="Ask policy questions. AI responds with reasoning.",
                additional_inputs=[
                    gr.Checkbox(True, label="Show metrics panel")
                ]
            )

        # Right side: Metrics panel
        with gr.Column(scale=1):
            metrics_panel = gr.Markdown(
                "### 📊 Metrics Panel\n\n*Send messages to see discourse metrics*",
                elem_classes="metrics"
            )

    gr.Markdown("""
    ---
    ### ℹ️ About This Prototype
    - **Framework:** Inspired by Speech-Centred Systems Theory (Meaning Load constraint)
    - **Metrics Tracked:** Length, complexity, sentiment, sentence count
    - **Tech Stack:** Gradio, HuggingFace Transformers, TextBlob
    - **Next Steps:** Integrate with voting interface, expand metric set
    """)

    # Export conversation feature (INSIDE Blocks context)
    export_btn = gr.Button("💾 Export Conversation Log", variant="secondary")
    export_output = gr.Textbox(label="Status", interactive=False)
    export_btn.click(export_conversation, outputs=export_output)

print("✓ Interface built with export functionality")

# Launch the app
demo.queue()  # Enable async queuing
demo.launch(share=False)  # Set True for public share link

print("✓ App launched - use the URL below!")

# Save Interactions
def export_conversation():
    """Export conversation history to CSV"""
    df = pd.DataFrame([{
        'turn': log['turn_number'],
        'user_input': log['user_input'],
        'ai_response': log['ai_response'],
        'user_words': log['user_metrics']['word_count'],
        'ai_words': log['ai_metrics']['word_count'],
        'sentiment': log['user_metrics']['sentiment_score']
    } for log in conversation_log])

    filename = f'deliberation_conversation_{datetime.now().strftime("%Y%m%d_%H%M%S")}.csv'
    df.to_csv(filename, index=False)

    return f"✓ Saved to {filename}"

# Test run
# Quick test without UI
test_messages = [
    "Should Switzerland introduce AI voting assistants?",
    "What are the risks of automated policy interpretation?",
    "Can citizens evaluate DC reasoning or just accuracy?"
]

for msg in test_messages:
    print(f"\n👤 User: {msg}")
    resp = respond(msg, [])
    print(f"🤖 AI: {resp}\n")

print("✓ Test run complete")

# Upload to Gihub
git init
#git add .
git commit -m "Deliberation component prototype - first iteration"
git branch -M main
git remote add origin https://github.com/amitverma86/HCI-HCAI.git
git push -u origin main